# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class D2vm < Formula
  desc "Build Virtual Machine Image from Dockerfile or Docker image"
  homepage "https://github.com/linka-cloud/d2vm"
  version "0.1.0-rc4"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/linka-cloud/d2vm/releases/download/v0.1.0-rc4/d2vm_v0.1.0-rc4_darwin_arm64.tar.gz"
      sha256 "746df4506c6fd0c35107d1096b1ec12e303be807ab843ef2af6f7eeef3d24f00"

      def install
        bin.install "d2vm"
        bash_completion.install "completions/d2vm.bash" => "d2vm"
        zsh_completion.install "completions/d2vm.zsh" => "_d2vm"
        fish_completion.install "completions/d2vm.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/linka-cloud/d2vm/releases/download/v0.1.0-rc4/d2vm_v0.1.0-rc4_darwin_amd64.tar.gz"
      sha256 "8be2172020c7cd0554389675ef432fc0856fc043585503d1b508863b401e35c8"

      def install
        bin.install "d2vm"
        bash_completion.install "completions/d2vm.bash" => "d2vm"
        zsh_completion.install "completions/d2vm.zsh" => "_d2vm"
        fish_completion.install "completions/d2vm.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/linka-cloud/d2vm/releases/download/v0.1.0-rc4/d2vm_v0.1.0-rc4_linux_arm64.tar.gz"
      sha256 "d218066e6d4e633ce19b6b985db21cb36c6653aa43237ecde3417725da76474c"

      def install
        bin.install "d2vm"
        bash_completion.install "completions/d2vm.bash" => "d2vm"
        zsh_completion.install "completions/d2vm.zsh" => "_d2vm"
        fish_completion.install "completions/d2vm.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/linka-cloud/d2vm/releases/download/v0.1.0-rc4/d2vm_v0.1.0-rc4_linux_amd64.tar.gz"
      sha256 "c586efbeb59d60e5ee8a5c2d2e4794945c1311a9922d253cff5ae01d1e210609"

      def install
        bin.install "d2vm"
        bash_completion.install "completions/d2vm.bash" => "d2vm"
        zsh_completion.install "completions/d2vm.zsh" => "_d2vm"
        fish_completion.install "completions/d2vm.fish"
      end
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  test do
    system "#{bin}/d2vm --version"
  end
end
