# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class D2vm < Formula
  desc "Build Virtual Machine Image from Dockerfile or Docker image"
  homepage "https://github.com/linka-cloud/d2vm"
  version "0.4.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/linka-cloud/d2vm/releases/download/v0.4.0/d2vm_v0.4.0_darwin_arm64.tar.gz"
      sha256 "ea252a8812df265533b5b856277980c39eb26d3327fa8d4c1090e68988628d4c"

      def install
        bin.install "d2vm"
        bash_completion.install "completions/d2vm.bash" => "d2vm"
        zsh_completion.install "completions/d2vm.zsh" => "_d2vm"
        fish_completion.install "completions/d2vm.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/linka-cloud/d2vm/releases/download/v0.4.0/d2vm_v0.4.0_darwin_amd64.tar.gz"
      sha256 "4dd0e9af2a60357e7a87092d135964699e22b3242c1e8b170fcc4ff20c33a766"

      def install
        bin.install "d2vm"
        bash_completion.install "completions/d2vm.bash" => "d2vm"
        zsh_completion.install "completions/d2vm.zsh" => "_d2vm"
        fish_completion.install "completions/d2vm.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/linka-cloud/d2vm/releases/download/v0.4.0/d2vm_v0.4.0_linux_arm64.tar.gz"
      sha256 "bb8a6c96557fba67b42a34a0777a65fd91af46fff523611b2cc9e28f801117c6"

      def install
        bin.install "d2vm"
        bash_completion.install "completions/d2vm.bash" => "d2vm"
        zsh_completion.install "completions/d2vm.zsh" => "_d2vm"
        fish_completion.install "completions/d2vm.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/linka-cloud/d2vm/releases/download/v0.4.0/d2vm_v0.4.0_linux_amd64.tar.gz"
      sha256 "9f2096bc7850367d063cbcf2da8ded6c5a23e70a9b0ecfdde150b2fbc9b8bd2f"

      def install
        bin.install "d2vm"
        bash_completion.install "completions/d2vm.bash" => "d2vm"
        zsh_completion.install "completions/d2vm.zsh" => "_d2vm"
        fish_completion.install "completions/d2vm.fish"
      end
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  test do
    system "#{bin}/d2vm --version"
  end
end
