# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lkar < Formula
  desc "Distribute your artifacts to your end users without any additional administration or maintenance costs."
  homepage "https://github.com/linka-cloud/artifact-registry"
  version "0.0.0"
  license "Apache 2.0 and MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/linka-cloud/artifact-registry/releases/download/v0.0.0/lkar_Darwin_aarch64.tar.gz"
      sha256 "954ca4900f5533ad07be6034ec4f21adedeb17ebfa9baa761978e3f02ce84e80"

      def install
        bin.install "lkar"
        bash_completion.install "completions/lkar.bash" => "lkar"
        zsh_completion.install "completions/lkar.zsh" => "_lkar"
        fish_completion.install "completions/lkar.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/linka-cloud/artifact-registry/releases/download/v0.0.0/lkar_Darwin_x86_64.tar.gz"
      sha256 "7ddd581ab0ddbac5d9281b90de4c6fb46d81221a9f0860cf414545ea4e4d1e5e"

      def install
        bin.install "lkar"
        bash_completion.install "completions/lkar.bash" => "lkar"
        zsh_completion.install "completions/lkar.zsh" => "_lkar"
        fish_completion.install "completions/lkar.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/linka-cloud/artifact-registry/releases/download/v0.0.0/lkar_Linux_aarch64.tar.gz"
      sha256 "ae681c5acee3ebd33a331cd0c47a5f6d8cde11bc257486f79fbf2f8e33eccb22"

      def install
        bin.install "lkar"
        bash_completion.install "completions/lkar.bash" => "lkar"
        zsh_completion.install "completions/lkar.zsh" => "_lkar"
        fish_completion.install "completions/lkar.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/linka-cloud/artifact-registry/releases/download/v0.0.0/lkar_Linux_x86_64.tar.gz"
      sha256 "a850c585f5d60b0805a3d67f0a87c361603a31a7ad2eff689720c43926d9a26c"

      def install
        bin.install "lkar"
        bash_completion.install "completions/lkar.bash" => "lkar"
        zsh_completion.install "completions/lkar.zsh" => "_lkar"
        fish_completion.install "completions/lkar.fish"
      end
    end
  end

  test do
    system "#{bin}/lkar --version"
  end
end
