# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lkar < Formula
  desc "Distribute your artifacts to your end users without any additional administration or maintenance costs."
  homepage "https://github.com/linka-cloud/artifact-registry"
  version "0.2.0"
  license "Apache 2.0 and MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/linka-cloud/artifact-registry/releases/download/v0.2.0/lkar_Darwin_aarch64.tar.gz"
      sha256 "a28900b9811665d99b6aae9ef3883b7820b33ecbe6433fd48c92d9bb2e453b49"

      def install
        bin.install "lkar"
        bash_completion.install "completions/lkar.bash" => "lkar"
        zsh_completion.install "completions/lkar.zsh" => "_lkar"
        fish_completion.install "completions/lkar.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/linka-cloud/artifact-registry/releases/download/v0.2.0/lkar_Darwin_x86_64.tar.gz"
      sha256 "16e35293c3152670e96ee486763be15e8cba93d8e3322214ae3a2ce161c96ad1"

      def install
        bin.install "lkar"
        bash_completion.install "completions/lkar.bash" => "lkar"
        zsh_completion.install "completions/lkar.zsh" => "_lkar"
        fish_completion.install "completions/lkar.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/linka-cloud/artifact-registry/releases/download/v0.2.0/lkar_Linux_aarch64.tar.gz"
      sha256 "97df7cfbefc5830cf9f1dd7ccd9282ba0b2e288cadd77ab8484797aa6dccbcb3"

      def install
        bin.install "lkar"
        bash_completion.install "completions/lkar.bash" => "lkar"
        zsh_completion.install "completions/lkar.zsh" => "_lkar"
        fish_completion.install "completions/lkar.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/linka-cloud/artifact-registry/releases/download/v0.2.0/lkar_Linux_x86_64.tar.gz"
      sha256 "5dc241c988dc7e865fdcdd2d04759085c966b23368ab16344407cee12937e485"

      def install
        bin.install "lkar"
        bash_completion.install "completions/lkar.bash" => "lkar"
        zsh_completion.install "completions/lkar.zsh" => "_lkar"
        fish_completion.install "completions/lkar.fish"
      end
    end
  end

  test do
    system "#{bin}/lkar --version"
  end
end
